### ISSUE TITLE
MUI ios16.4 选择器滑动的数据出现白条 日期选择也出现错位白条

### ISSUE THREAD

**Issue by icecola0303** [dcloudio/mui#525]

**Comment by 83628410** [comment]
.mui-picker-inner {
	position: relative;
	width: 100%;
	height: 100%;
	/*-webkit-mask-box-image: -webkit-linear-gradient(bottom, transparent, transparent 5%, #fff 20%, #fff 80%, transparent 95%, transparent);*/
	/*-webkit-mask-box-image: linear-gradient(top, transparent, transparent 5%, #fff 20%, #fff 80%, transparent 95%, transparent)*/
}

注释掉就可以了

**Comment by sutra** [comment]
```css
@supports (margin-trim: block) {
	/* Supported from Safari 16.4 */
	/* https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes */

	.mui-picker-inner {
		-webkit-mask-box-image: unset;
	}
}
```
